shopify:
  shop_url: your-store.myshopify.com
  api_key: your_api_key_here
  password: your_api_password_here

ebay:
  app_id: your_app_id_here
  cert_id: your_cert_id_here
  dev_id: your_dev_id_here
  auth_token: your_auth_token_here
  sandbox_mode: true

google:
  api_key: your_google_api_key_here
  custom_search_id: your_custom_search_engine_id_here
