services:
  - type: web
    name: dropchipai-backend
    env: python
    buildCommand: pip install -r DropchipAI/backend/requirements.txt
    startCommand: cd DropchipAI/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PORT
        value: 10000 